import { WORKSPACE_CONTRACT_VERSION } from "@codexhost/shared-contracts";

export { validateHostApprovalResponse } from "./approval.js";
export { validateHostInteractionResponse } from "./interaction.js";
export { HarnessOutputChannel } from "./output-channel.js";
export { validateHostQuestionResponse } from "./question.js";
export { parseHostUsage } from "./usage.js";
export type { HostUsage } from "./usage.js";
export type {
  CreateSessionInput,
  ForkSessionInput,
  HarnessAdapter,
  HarnessError,
  HarnessErrorCode,
  HarnessInspection,
  HarnessModel,
  HarnessModelCatalog,
  HarnessModelRef,
  HarnessOutput,
  HarnessResult,
  HarnessSession,
  HarnessSessionCapabilities,
  HarnessSessionState,
  HarnessThinkingOption,
  HarnessThinkingOptionId,
  HostAgentMessageItem,
  HostApprovalAction,
  HostApprovalEffect,
  HostApprovalInteraction,
  HostApprovalResponse,
  HostChoiceQuestion,
  HostCommand,
  HostCommandExecutionItem,
  HostEvent,
  HostFileChange,
  HostFileChangeItem,
  HistoricalTurnOutcome,
  HostInteraction,
  HostInteractionResponse,
  HostItem,
  HostItemOutcome,
  HostItemSnapshot,
  HostItemUpdate,
  HostQuestion,
  HostQuestionInteraction,
  HostQuestionResponse,
  HostThreadSnapshot,
  HostTextInput,
  HostTextQuestion,
  HostToolExecutionItem,
  HostToolOutput,
  HostTurnSnapshot,
  InteractionClosedEvent,
  InteractionRespondAccepted,
  InteractionRespondCommand,
  ItemCompletedEvent,
  ItemStartedEvent,
  InspectHarnessInput,
  ItemUpdatedEvent,
  ModelSelectCommand,
  ModelSelectCompleted,
  OpenSessionInput,
  ResumeSessionInput,
  SessionFaultedEvent,
  SessionStateChangedEvent,
  SessionUsageChangedEvent,
  ThinkingSelectCommand,
  ThinkingSelectCompleted,
  TurnCompletedEvent,
  TurnCancelAccepted,
  TurnCancelCommand,
  TurnOutcome,
  TurnStartAccepted,
  TurnStartCommand,
  TurnStartedEvent,
} from "./text-session.js";

export const packageMetadata = {
  name: "@codexhost/harness-adapter",
  contractVersion: WORKSPACE_CONTRACT_VERSION,
} as const;
