// Runs only inside desktop-services.mjs's disposable, offline native Host sandbox.
import assert from "node:assert/strict";
import { ZcodeAdapter, ZcodeError } from "./adapter.mjs";

export async function probeAdapter(channel, cwd, fixtureChannel) {
  const fixtureCall = (method, params) => fixtureChannel.call(method, [params]);
  const call = async (method, params) => {
    try {
      return await channel.call(method, [params]);
    } catch (error) {
      throw new ZcodeError(
        error.code === -32004 ? "sessionNotFound" : "nativeFailure",
        `Fixture ${method} failed (${Number(error.code)})`,
        false,
        error.code,
      );
    }
  };
  const hello = await call("helloConversationV4", {});
  assert.equal(hello.protocolVersion, 3);
  assert.equal(hello.clientMode, "web-remote-replayable");
  const clientId = "codexhost-fixture";
  await call("initializeConversationV4", {
    kind: "clientHello",
    protocolVersion: 3,
    clientId,
    clientKind: "web",
    appVersion: "3.12.3",
  });
  const service = {
    workspace: { workspacePath: cwd },
    desktopId: "fixture-device",
    deviceSid: "fixture-device",
    clientId,
    call,
    listen: async (method, params, listener) => {
      const disposable = channel.listen(method, [params])(listener);
      return async () => disposable.dispose();
    },
    onFault: () => () => {},
    invalidate: () => {
      throw new Error("Native fixture connection invalidated");
    },
    close: async () => {},
  };
  const options = {
    environment: { CODEXHOST_DATA_DIR: cwd },
    desktopServiceFactory: async () => service,
  };
  const configure = new ZcodeAdapter(options);
  assert.equal(
    (
      await configure.connection.set(
        `https://zcode.z.ai/remote/v4?sid=fixture-device&hash=${encodeURIComponent(Buffer.alloc(32, 8).toString("base64"))}&app_version=3.12.3`,
        cwd,
      )
    ).ok,
    true,
  );
  await configure.close();
  const adapter = new ZcodeAdapter(options);
  try {
    const inspection = await adapter.inspect(); // Same workspace-free request sent by the Picker.
    assert.equal(inspection.status, "ready", JSON.stringify(inspection));
    assert.equal(inspection.catalog.models.length, 1);
    assert.match(inspection.catalog.models[0].ref.id, /^zcode-desktop-v1\./u);
    const first = await adapter.open({ kind: "create", cwd });
    assert.equal(first.ok, true, JSON.stringify(first.ok ? {} : first.error));
    const second = await adapter.open({ kind: "create", cwd });
    assert.equal(second.ok, true, JSON.stringify(second.ok ? {} : second.error));
    assert.notEqual(
      first.value.initialState.nativeRef.nativeSessionId,
      second.value.initialState.nativeRef.nativeSessionId,
    );
    const ref = first.value.initialState.nativeRef;
    assert.equal((await first.value.readSnapshot()).ok, true);
    await first.value.close();
    // Native create does not persist a record until there is actual history. Do not
    // turn a closed empty Session into a different Session or import to fake its ID.
    assert.equal(
      (await fixtureCall("listSessions", { workspacePath: cwd, sessionIds: [ref.nativeSessionId] }))
        .length,
      0,
    );
    assert.equal((await second.value.readSnapshot()).ok, true);
    const empty = await adapter.open({ kind: "resume", cwd, nativeRef: ref });
    assert.equal(empty.ok, false);
    assert.equal(empty.error.code, "sessionNotFound");
    // Seed a separate, explicitly synthetic history using the native import API.
    // This is fixture setup only, never an Adapter create/recovery workaround.
    const seeded = await fixtureCall("createSession", {
      workspacePath: cwd,
      titleGenerationEnabled: false,
      mcpServers: [],
      importedHistory: {
        source: "claudeCode",
        title: "Synthetic persistence fixture",
        messages: [
          { role: "user", content: "Fixture input (not sent to a model)" },
          { role: "assistant", content: "Fixture reply (not generated by a model)" },
        ],
      },
    });
    const savedRef = { ...ref, nativeSessionId: seeded.session.sessionId };
    await call("closeSession", { workspacePath: cwd, sessionId: savedRef.nativeSessionId });
    let previous;
    for (let index = 0; index < 2; index++) {
      const resumed = await adapter.open({ kind: "resume", cwd, nativeRef: savedRef });
      assert.equal(resumed.ok, true, JSON.stringify(resumed.ok ? {} : resumed.error));
      assert.deepEqual(resumed.value.initialState.nativeRef, savedRef);
      const history = await resumed.value.readSnapshot();
      assert.equal(history.ok, true);
      assert.equal(history.value.turns.length, 1);
      if (previous) assert.deepEqual(history.value, previous);
      previous = history.value;
      await resumed.value.close();
    }
  } finally {
    await adapter.close();
  }
}
